[package]
name = "presentation"
version = "0.1.0"
authors = ["Danny Fritz <dannyfritz@gmail.com>"]

[dependencies]
vulkano = "0.9"
vulkano-win = "0.9"
# vulkano_shader_derive = ""
winit = "0.11"
nalgebra = "0.14"

[features]
default = ["vk_debug"]
vk_debug = []